In [5]:
import numpy as np
List = [2440,6052,6371,3390,69911,58232,25362,24622]
pl = np.array(List)
vol = 4/3 * np.pi * pl**3
vol

array([ 6.87749971e+09, -7.00988505e+09,  3.76390048e+09,  1.27135369e+09,
       -5.65680552e+09,  6.70386370e+09,  5.61275988e+09,  7.96262314e+09])

In [4]:
import numpy as np

List = [2440, 6052, 6371, 3390, 69911, 58232, 25362, 24622]
pl = np.abs(np.array(List, dtype=np.int64))  # Take the absolute values of the elements
vol = (4 / 3) * 3.141592653589793 * pl**3
vol


array([6.08496505e+10, 9.28507396e+11, 1.08320692e+12, 1.63187806e+11,
       1.43128181e+15, 8.27129915e+14, 6.83343557e+13, 6.25257040e+13])

In [6]:
List = [2440, 6052, 6371, 3390, 69911, 58232, 25362, 24622]
pl = np.abs(np.array(List, dtype=np.float32))  # Take the absolute values of the elements
vol = (4 / 3) * np.pi * pl**3
vol

array([6.0849652e+10, 9.2850736e+11, 1.0832069e+12, 1.6318782e+11,
       1.4312819e+15, 8.2712990e+14, 6.8334360e+13, 6.2525706e+13],
      dtype=float32)