# Numpy

                                                                                                              22.06.2023

In [2]:
import numpy as np

In [3]:
List = [45,85,1000,25,47,51]

In [4]:
print(List)
print(type(List))

[45, 85, 1000, 25, 47, 51]
<class 'list'>


In [5]:
nparr = np.array(List)

In [6]:
nparr

array([  45,   85, 1000,   25,   47,   51])

In [7]:
type(nparr)

numpy.ndarray

In [8]:
List1 = range(1000)

In [9]:
nparr = np.array(List1)

In [10]:
%timeit [i**2 for i in List1]

711 µs ± 22.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [11]:
%timeit nparr**2

3.75 µs ± 22.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### 1D array

In [12]:
nparr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

dimention

In [13]:
nparr.ndim

1

Length

In [14]:
len(nparr)

1000

In [15]:
nparr.shape

(1000,)

### 2D array

In [16]:
nparr2 = np.array([2,4,5,10])

In [17]:
nparr2.ndim

1

In [18]:
nparr = np.array([[2,4,5,10],[4,7,9,20]])

In [19]:
nparr2.shape

(4,)

### 3D array

In [20]:
nparr3 = np.array([[[4,5,6,7],[7,8,9,10]]])

In [21]:
nparr3.ndim

3

In [22]:
nparr.shape

(2, 4)

In [23]:
nparr4 = np.array(range(0,50)) 

In [24]:
nparr4.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [25]:
nparr4.reshape(1,5,10)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]])

In [26]:
nparr4.reshape(2,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [27]:
nparr4.reshape(5,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [28]:
nparr4.reshape(1,2,5,5)

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]]])

In [29]:
nparr4 = np.mat([1,2,3,4])
nparr4.shape

(1, 4)

-----------------------------------------------------------------------

Slicing (H.W)

In [40]:
#1D array
arr = np.array([10,20,30,40,50,60,70])

In [41]:
arr[1:3]

array([20, 30])

In [44]:
arr[1:6:2]

array([20, 40, 60])

In [45]:
arr[::2]

array([10, 30, 50, 70])

In [46]:
arr[-4:-2]

array([40, 50])

In [47]:
arr[::-1]

array([70, 60, 50, 40, 30, 20, 10])