# AILABS DAY 5

                                                                                                                23.06.2023

In [1]:
import numpy as np

In [19]:
arr2 = np.random.rand(150,4)
arr2

array([[7.14854650e-01, 6.34925174e-01, 1.90843385e-01, 6.22338597e-01],
       [6.88225461e-01, 7.44733434e-02, 7.46477635e-01, 8.72122656e-01],
       [5.51928004e-01, 2.73755927e-01, 1.61942993e-01, 9.22166328e-01],
       [1.66046185e-01, 2.61402278e-01, 9.47676119e-01, 6.40783895e-01],
       [8.82649806e-01, 9.72334669e-01, 9.74062385e-01, 4.77527904e-01],
       [7.13669024e-02, 3.54364527e-01, 8.57896019e-01, 2.09084408e-01],
       [7.14678419e-01, 9.61550763e-01, 4.26373912e-01, 4.98392607e-02],
       [6.99227089e-01, 3.66365480e-01, 7.39455836e-02, 2.94520233e-01],
       [9.40951619e-01, 9.10836490e-01, 4.76779967e-01, 9.59742025e-01],
       [8.29734855e-01, 5.22742416e-01, 5.54220472e-01, 5.46763697e-01],
       [6.38882864e-01, 8.01015202e-01, 5.63751539e-01, 6.36482567e-01],
       [1.67816775e-01, 8.48822279e-02, 4.27702417e-02, 4.64802650e-01],
       [5.75336360e-01, 9.07286421e-01, 8.73186997e-01, 7.47757203e-01],
       [3.33830251e-01, 1.51880901e-01, 7.37998192e

In [11]:
np.random.randint(150,200)

152

In [12]:
arr = np.arange(0,50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [13]:
arr[2:20]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [17]:
arr[arr>0.5]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
arr[0:4][:]

array([0, 1, 2, 3])

In [29]:
arr2[arr2>0.5]

array([0.71485465, 0.63492517, 0.6223386 , 0.68822546, 0.74647763,
       0.87212266, 0.551928  , 0.92216633, 0.94767612, 0.6407839 ,
       0.88264981, 0.97233467, 0.97406239, 0.85789602, 0.71467842,
       0.96155076, 0.69922709, 0.94095162, 0.91083649, 0.95974203,
       0.82973486, 0.52274242, 0.55422047, 0.5467637 , 0.63888286,
       0.8010152 , 0.56375154, 0.63648257, 0.57533636, 0.90728642,
       0.873187  , 0.7477572 , 0.73799819, 0.78209135, 0.9356433 ,
       0.80273956, 0.71103469, 0.75442637, 0.57188784, 0.5777945 ,
       0.94977214, 0.62847284, 0.65179478, 0.96486255, 0.60330474,
       0.75377659, 0.85110658, 0.58956476, 0.99132849, 0.8942848 ,
       0.98731648, 0.65517099, 0.73491509, 0.57466271, 0.68898093,
       0.71166919, 0.70959236, 0.92849866, 0.95439505, 0.5971228 ,
       0.51419937, 0.97151813, 0.85924544, 0.88185274, 0.70872955,
       0.53850516, 0.69885568, 0.62610513, 0.53373658, 0.85315218,
       0.68812307, 0.77174672, 0.80801652, 0.66719288, 0.96680

In [32]:
arr2[0:4][1:2]

array([[0.68822546, 0.07447334, 0.74647763, 0.87212266]])

In [28]:
arr2[0:4,[1,2]]

array([[0.63492517, 0.19084338],
       [0.07447334, 0.74647763],
       [0.27375593, 0.16194299],
       [0.26140228, 0.94767612]])

In [36]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
a*b  #elements wise multiplication

array([[ 1,  4],
       [ 9, 16]])

In [40]:
a@b  #matrix multiplication 

array([[ 7, 10],
       [15, 22]])

In [42]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [44]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [45]:
np.zeros((3,5,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [49]:
np.ones([3,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
np.ones([1,3,6])

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [54]:
5+np.ones([3,6])

array([[6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6.]])

In [58]:
#empty array
np.empty([4,5])

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261434e-306, 6.89805830e-307],
       [9.79101761e-307, 7.56596412e-307, 1.11256817e-306,
        1.06811422e-306, 1.42417221e-306],
       [1.11260619e-306, 8.90094053e-307, 1.86919378e-306,
        1.06809792e-306, 1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307, 5.33590898e-322]])

In [60]:
#LinSpace - represent the liner space 
np.linspace(3,7)

array([3.        , 3.08163265, 3.16326531, 3.24489796, 3.32653061,
       3.40816327, 3.48979592, 3.57142857, 3.65306122, 3.73469388,
       3.81632653, 3.89795918, 3.97959184, 4.06122449, 4.14285714,
       4.2244898 , 4.30612245, 4.3877551 , 4.46938776, 4.55102041,
       4.63265306, 4.71428571, 4.79591837, 4.87755102, 4.95918367,
       5.04081633, 5.12244898, 5.20408163, 5.28571429, 5.36734694,
       5.44897959, 5.53061224, 5.6122449 , 5.69387755, 5.7755102 ,
       5.85714286, 5.93877551, 6.02040816, 6.10204082, 6.18367347,
       6.26530612, 6.34693878, 6.42857143, 6.51020408, 6.59183673,
       6.67346939, 6.75510204, 6.83673469, 6.91836735, 7.        ])

In [61]:
np.linspace(3,7,10)    

array([3.        , 3.44444444, 3.88888889, 4.33333333, 4.77777778,
       5.22222222, 5.66666667, 6.11111111, 6.55555556, 7.        ])

In [64]:
np.linspace(3,7,5, endpoint = False)

array([3. , 3.8, 4.6, 5.4, 6.2])

In [65]:
np.linspace(3,7,5,retstep = True)

(array([3., 4., 5., 6., 7.]), 1.0)

In [62]:
#logspace
np.logspace(3,6,4)

array([   1000.,   10000.,  100000., 1000000.])

In [74]:
var2 = np.arange(4,54)
var2

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53])

In [79]:
var2 = var2.reshape(5,-1)
var2

array([[ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53]])

In [81]:
pow(var2,2)

array([[  16,   25,   36,   49,   64,   81,  100,  121,  144,  169],
       [ 196,  225,  256,  289,  324,  361,  400,  441,  484,  529],
       [ 576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089],
       [1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849],
       [1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809]],
      dtype=int32)

In [87]:
print(var2.max())
print(var2.argmax())

53
49


In [85]:
var2.max(axis=0)

array([44, 45, 46, 47, 48, 49, 50, 51, 52, 53])

In [86]:
var2.max(axis = 1)

array([13, 23, 33, 43, 53])

In [88]:
var2.T

array([[ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45],
       [ 6, 16, 26, 36, 46],
       [ 7, 17, 27, 37, 47],
       [ 8, 18, 28, 38, 48],
       [ 9, 19, 29, 39, 49],
       [10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52],
       [13, 23, 33, 43, 53]])

In [89]:
np.exp(var2)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
        1.62754791e+05, 4.42413392e+05],
       [1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
        6.56599691e+07, 1.78482301e+08, 4.85165195e+08, 1.31881573e+09,
        3.58491285e+09, 9.74480345e+09],
       [2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
        1.44625706e+12, 3.93133430e+12, 1.06864746e+13, 2.90488497e+13,
        7.89629602e+13, 2.14643580e+14],
       [5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16, 2.35385267e+17, 6.39843494e+17,
        1.73927494e+18, 4.72783947e+18],
       [1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
        7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22,
        3.83100800e+22, 1.04137594e+23]])

In [90]:
np.log(var2)

array([[1.38629436, 1.60943791, 1.79175947, 1.94591015, 2.07944154,
        2.19722458, 2.30258509, 2.39789527, 2.48490665, 2.56494936],
       [2.63905733, 2.7080502 , 2.77258872, 2.83321334, 2.89037176,
        2.94443898, 2.99573227, 3.04452244, 3.09104245, 3.13549422],
       [3.17805383, 3.21887582, 3.25809654, 3.29583687, 3.33220451,
        3.36729583, 3.40119738, 3.4339872 , 3.4657359 , 3.49650756],
       [3.52636052, 3.55534806, 3.58351894, 3.61091791, 3.63758616,
        3.66356165, 3.68887945, 3.71357207, 3.73766962, 3.76120012],
       [3.78418963, 3.80666249, 3.8286414 , 3.8501476 , 3.87120101,
        3.8918203 , 3.91202301, 3.93182563, 3.95124372, 3.97029191]])

In [91]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [92]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

indentity and eye are same.